<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>42.Platform.Cli.UnitTests</AssemblyName>
    <RootNamespace>_42.Platform.Cli.UnitTests</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JsonPatch.Net" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Cli.csproj" />
  </ItemGroup>

</Project>
