// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace _42.Monorepo.Cli.Templates
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class DotVsConfigT4 : DotVsConfigT4Base
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("{\r\n  \"version\": \"1.0\",\r\n  \"components\": [\r\n    \"Microsoft.VisualStudio.Component." +
                    "CoreEditor\",\r\n    \"Microsoft.VisualStudio.Workload.CoreEditor\",\r\n    \"Microsoft." +
                    "Net.Component.4.8.SDK\",\r\n    \"Microsoft.Net.Component.4.7.2.TargetingPack\",\r\n   " +
                    " \"Microsoft.Net.ComponentGroup.DevelopmentPrerequisites\",\r\n    \"Microsoft.Visual" +
                    "Studio.Component.TypeScript.TSServer\",\r\n    \"Microsoft.VisualStudio.ComponentGro" +
                    "up.WebToolsExtensions\",\r\n    \"Microsoft.VisualStudio.Component.JavaScript.TypeSc" +
                    "ript\",\r\n    \"Microsoft.VisualStudio.Component.JavaScript.Diagnostics\",\r\n    \"Mic" +
                    "rosoft.VisualStudio.Component.Roslyn.Compiler\",\r\n    \"Microsoft.Component.MSBuil" +
                    "d\",\r\n    \"Microsoft.VisualStudio.Component.Roslyn.LanguageServices\",\r\n    \"Micro" +
                    "soft.VisualStudio.Component.TextTemplating\",\r\n    \"Component.Microsoft.VisualStu" +
                    "dio.RazorExtension\",\r\n    \"Microsoft.VisualStudio.Component.IISExpress\",\r\n    \"M" +
                    "icrosoft.VisualStudio.Component.NuGet\",\r\n    \"Microsoft.VisualStudio.Component.M" +
                    "SODBC.SQL\",\r\n    \"Microsoft.VisualStudio.Component.SQL.LocalDB.Runtime\",\r\n    \"M" +
                    "icrosoft.VisualStudio.Component.Common.Azure.Tools\",\r\n    \"Microsoft.VisualStudi" +
                    "o.Component.SQL.CLR\",\r\n    \"Microsoft.VisualStudio.Component.MSSQL.CMDLnUtils\",\r" +
                    "\n    \"Microsoft.Component.ClickOnce\",\r\n    \"Microsoft.VisualStudio.Component.Man" +
                    "agedDesktop.Core\",\r\n    \"Microsoft.VisualStudio.Component.SQL.SSDT\",\r\n    \"Micro" +
                    "soft.VisualStudio.Component.SQL.DataSources\",\r\n    \"Component.Microsoft.Web.Libr" +
                    "aryManager\",\r\n    \"Component.Microsoft.WebTools.BrowserLink.WebLivePreview\",\r\n  " +
                    "  \"Microsoft.VisualStudio.ComponentGroup.Web\",\r\n    \"Microsoft.NetCore.Component" +
                    ".Runtime.6.0\",\r\n    \"Microsoft.NetCore.Component.SDK\",\r\n    \"Microsoft.VisualStu" +
                    "dio.Component.FSharp\",\r\n    \"Microsoft.ComponentGroup.ClickOnce.Publish\",\r\n    \"" +
                    "Microsoft.NetCore.Component.DevelopmentTools\",\r\n    \"Microsoft.VisualStudio.Comp" +
                    "onent.FSharp.WebTemplates\",\r\n    \"Microsoft.VisualStudio.Component.DockerTools\"," +
                    "\r\n    \"Microsoft.NetCore.Component.Web\",\r\n    \"Microsoft.VisualStudio.Component." +
                    "WebDeploy\",\r\n    \"Microsoft.VisualStudio.Component.AppInsights.Tools\",\r\n    \"Mic" +
                    "rosoft.VisualStudio.Component.Web\",\r\n    \"Microsoft.Net.Component.4.8.TargetingP" +
                    "ack\",\r\n    \"Microsoft.Net.ComponentGroup.4.8.DeveloperTools\",\r\n    \"Component.Mi" +
                    "crosoft.VisualStudio.Web.AzureFunctions\",\r\n    \"Microsoft.VisualStudio.Component" +
                    "Group.AzureFunctions\",\r\n    \"Microsoft.VisualStudio.ComponentGroup.Web.CloudTool" +
                    "s\",\r\n    \"Microsoft.VisualStudio.Component.DiagnosticTools\",\r\n    \"Microsoft.Vis" +
                    "ualStudio.Component.Debugger.JustInTime\",\r\n    \"Component.Microsoft.VisualStudio" +
                    ".LiveShare.2022\",\r\n    \"Microsoft.VisualStudio.Workload.NetWeb\",\r\n    \"Microsoft" +
                    ".VisualStudio.Component.Azure.ClientLibs\",\r\n    \"Microsoft.VisualStudio.Componen" +
                    "tGroup.Azure.Prerequisites\",\r\n    \"Microsoft.VisualStudio.Component.Azure.Resour" +
                    "ceManager.Tools\",\r\n    \"Microsoft.VisualStudio.ComponentGroup.Azure.ResourceMana" +
                    "ger.Tools\",\r\n    \"Microsoft.VisualStudio.Component.Azure.AuthoringTools\",\r\n    \"" +
                    "Microsoft.VisualStudio.Component.Azure.Waverton.BuildTools\",\r\n    \"Microsoft.Vis" +
                    "ualStudio.Component.Azure.Compute.Emulator\",\r\n    \"Microsoft.VisualStudio.Compon" +
                    "ent.Azure.Waverton\",\r\n    \"Microsoft.VisualStudio.ComponentGroup.Azure.CloudServ" +
                    "ices\",\r\n    \"Microsoft.VisualStudio.Component.Azure.Powershell\",\r\n    \"Microsoft" +
                    ".VisualStudio.Workload.Azure\"\r\n  ]\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class DotVsConfigT4Base
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
