// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.V1.Item.Item.Item.Configuration.Item.Diff.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.V1.Item.Item.Item.Configuration.Item.Diff
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\{organization}\{project}\{view}\configuration\{key}\diff
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DiffRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ApiSdk.v1.item.item.item.configuration.item.diff.item collection</summary>
        /// <param name="position">The target view name.</param>
        /// <returns>A <see cref="global::ApiSdk.V1.Item.Item.Item.Configuration.Item.Diff.Item.WithViewToItemRequestBuilder"/></returns>
        public global::ApiSdk.V1.Item.Item.Item.Configuration.Item.Diff.Item.WithViewToItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("viewTo", position);
                return new global::ApiSdk.V1.Item.Item.Item.Configuration.Item.Diff.Item.WithViewToItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Item.Item.Item.Configuration.Item.Diff.DiffRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DiffRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/{organization}/{project}/{view}/configuration/{key}/diff", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Item.Item.Item.Configuration.Item.Diff.DiffRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DiffRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/{organization}/{project}/{view}/configuration/{key}/diff", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
