// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.V1.Item.Item.Item.Annotations;
using ApiSdk.V1.Item.Item.Item.Configuration;
using ApiSdk.V1.Item.Item.Item.Contexts;
using ApiSdk.V1.Item.Item.Item.Executions;
using ApiSdk.V1.Item.Item.Item.Responsibilities;
using ApiSdk.V1.Item.Item.Item.Subjects;
using ApiSdk.V1.Item.Item.Item.Units;
using ApiSdk.V1.Item.Item.Item.UnitsOfExecution;
using ApiSdk.V1.Item.Item.Item.Usages;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.V1.Item.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\{organization}\{project}\{view}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithViewItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The annotations property</summary>
        public global::ApiSdk.V1.Item.Item.Item.Annotations.AnnotationsRequestBuilder Annotations
        {
            get => new global::ApiSdk.V1.Item.Item.Item.Annotations.AnnotationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The configuration property</summary>
        public global::ApiSdk.V1.Item.Item.Item.Configuration.ConfigurationRequestBuilder Configuration
        {
            get => new global::ApiSdk.V1.Item.Item.Item.Configuration.ConfigurationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contexts property</summary>
        public global::ApiSdk.V1.Item.Item.Item.Contexts.ContextsRequestBuilder Contexts
        {
            get => new global::ApiSdk.V1.Item.Item.Item.Contexts.ContextsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The executions property</summary>
        public global::ApiSdk.V1.Item.Item.Item.Executions.ExecutionsRequestBuilder Executions
        {
            get => new global::ApiSdk.V1.Item.Item.Item.Executions.ExecutionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The responsibilities property</summary>
        public global::ApiSdk.V1.Item.Item.Item.Responsibilities.ResponsibilitiesRequestBuilder Responsibilities
        {
            get => new global::ApiSdk.V1.Item.Item.Item.Responsibilities.ResponsibilitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subjects property</summary>
        public global::ApiSdk.V1.Item.Item.Item.Subjects.SubjectsRequestBuilder Subjects
        {
            get => new global::ApiSdk.V1.Item.Item.Item.Subjects.SubjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The units property</summary>
        public global::ApiSdk.V1.Item.Item.Item.Units.UnitsRequestBuilder Units
        {
            get => new global::ApiSdk.V1.Item.Item.Item.Units.UnitsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unitsOfExecution property</summary>
        public global::ApiSdk.V1.Item.Item.Item.UnitsOfExecution.UnitsOfExecutionRequestBuilder UnitsOfExecution
        {
            get => new global::ApiSdk.V1.Item.Item.Item.UnitsOfExecution.UnitsOfExecutionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The usages property</summary>
        public global::ApiSdk.V1.Item.Item.Item.Usages.UsagesRequestBuilder Usages
        {
            get => new global::ApiSdk.V1.Item.Item.Item.Usages.UsagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Item.Item.Item.WithViewItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithViewItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/{organization}/{project}/{view}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Item.Item.Item.WithViewItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithViewItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/{organization}/{project}/{view}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
