/**
 * 2S-API
 * The 2S-API is a RESTful API for interacting with the 2S Platform.
 *
 * The version of the OpenAPI document: 0.8.26.4237
 * Contact: kobr.ales@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ExceptionWrapper {
    'message'?: string;
    'source'?: string;
    'stackTrace'?: string;
    'helpLink'?: string;
    'hResult'?: number;
    'innerException'?: ExceptionWrapper;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "Message",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "Source",
            "type": "string"
        },
        {
            "name": "stackTrace",
            "baseName": "StackTrace",
            "type": "string"
        },
        {
            "name": "helpLink",
            "baseName": "HelpLink",
            "type": "string"
        },
        {
            "name": "hResult",
            "baseName": "HResult",
            "type": "number"
        },
        {
            "name": "innerException",
            "baseName": "InnerException",
            "type": "ExceptionWrapper"
        }    ];

    static getAttributeTypeMap() {
        return ExceptionWrapper.attributeTypeMap;
    }
}

