/**
 * 2S-API
 * The 2S-API is a RESTful API for interacting with the 2S Platform.
 *
 * The version of the OpenAPI document: 0.8.26.4237
 * Contact: kobr.ales@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Permission {
    'createdById'?: string;
    'accountId'?: string;
    'accessPointKey'?: string;
    'role'?: Permission.RoleEnum = Permission.RoleEnum.None;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createdById",
            "baseName": "CreatedById",
            "type": "string"
        },
        {
            "name": "accountId",
            "baseName": "AccountId",
            "type": "string"
        },
        {
            "name": "accessPointKey",
            "baseName": "AccessPointKey",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "Role",
            "type": "Permission.RoleEnum"
        }    ];

    static getAttributeTypeMap() {
        return Permission.attributeTypeMap;
    }
}

export namespace Permission {
    export enum RoleEnum {
        None = <any> 'None',
        Reader = <any> 'Reader',
        Contributor = <any> 'Contributor',
        Administrator = <any> 'Administrator',
        Owner = <any> 'Owner'
    }
}
