<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>42.Platform.Storyteller.Backend.Certificates.Azure.KeyVault</AssemblyName>
    <RootNamespace>_42.Platform.Storyteller</RootNamespace>

    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Security.KeyVault.Keys" />
    <PackageReference Include="Microsoft.Extensions.Azure" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Backend.Core\src\Backend.Core.csproj" />
    <ProjectReference Include="..\..\..\..\Libraries\Utils\Async\src\Async.csproj" />
  </ItemGroup>

</Project>
