// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.V1.Item.Item.Access;
using ApiSdk.V1.Item.Item.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.V1.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\{organization}\{project}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProjectItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The access property</summary>
        public global::ApiSdk.V1.Item.Item.Access.AccessRequestBuilder Access
        {
            get => new global::ApiSdk.V1.Item.Item.Access.AccessRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the ApiSdk.v1.item.item.item collection</summary>
        /// <param name="position">The target view inside the project.</param>
        /// <returns>A <see cref="global::ApiSdk.V1.Item.Item.Item.WithViewItemRequestBuilder"/></returns>
        public global::ApiSdk.V1.Item.Item.Item.WithViewItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("view", position);
                return new global::ApiSdk.V1.Item.Item.Item.WithViewItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Item.Item.WithProjectItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProjectItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/{organization}/{project}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Item.Item.WithProjectItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProjectItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/{organization}/{project}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
