// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Annotation : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AnnotationKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnnotationKey { get; set; }
#nullable restore
#else
        public string AnnotationKey { get; set; }
#endif
        /// <summary>The AnnotationType property</summary>
        public global::ApiSdk.Models.Annotation_AnnotationType? AnnotationType { get; set; }
        /// <summary>The Description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The DocumentationLink property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentationLink { get; set; }
#nullable restore
#else
        public string DocumentationLink { get; set; }
#endif
        /// <summary>The ExpiresAt property</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>The IsDisabled property</summary>
        public bool? IsDisabled { get; set; }
        /// <summary>The Labels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Labels { get; set; }
#nullable restore
#else
        public List<string> Labels { get; set; }
#endif
        /// <summary>The Name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The ProjectName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectName { get; set; }
#nullable restore
#else
        public string ProjectName { get; set; }
#endif
        /// <summary>The TimeZone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeZone { get; set; }
#nullable restore
#else
        public string TimeZone { get; set; }
#endif
        /// <summary>The Title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The ValidFrom property</summary>
        public DateTimeOffset? ValidFrom { get; set; }
        /// <summary>The Values property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.Annotation_Values? Values { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.Annotation_Values Values { get; set; }
#endif
        /// <summary>The ViewName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ViewName { get; set; }
#nullable restore
#else
        public string ViewName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.Annotation"/> and sets the default values.
        /// </summary>
        public Annotation()
        {
            AdditionalData = new Dictionary<string, object>();
            AnnotationType = global::ApiSdk.Models.Annotation_AnnotationType.Responsibility;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.Annotation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.Annotation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("AnnotationType")?.GetStringValue();
            return mappingValue switch
            {
                "Context" => new global::ApiSdk.Models.Context(),
                "Execution" => new global::ApiSdk.Models.Execution(),
                "Responsibility" => new global::ApiSdk.Models.Responsibility(),
                "Subject" => new global::ApiSdk.Models.Subject(),
                "Unit" => new global::ApiSdk.Models.Unit(),
                "UnitOfExecution" => new global::ApiSdk.Models.UnitOfExecution(),
                "Usage" => new global::ApiSdk.Models.Usage(),
                _ => new global::ApiSdk.Models.Annotation(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AnnotationKey", n => { AnnotationKey = n.GetStringValue(); } },
                { "AnnotationType", n => { AnnotationType = n.GetEnumValue<global::ApiSdk.Models.Annotation_AnnotationType>(); } },
                { "Description", n => { Description = n.GetStringValue(); } },
                { "DocumentationLink", n => { DocumentationLink = n.GetStringValue(); } },
                { "ExpiresAt", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "IsDisabled", n => { IsDisabled = n.GetBoolValue(); } },
                { "Labels", n => { Labels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "Name", n => { Name = n.GetStringValue(); } },
                { "ProjectName", n => { ProjectName = n.GetStringValue(); } },
                { "TimeZone", n => { TimeZone = n.GetStringValue(); } },
                { "Title", n => { Title = n.GetStringValue(); } },
                { "ValidFrom", n => { ValidFrom = n.GetDateTimeOffsetValue(); } },
                { "Values", n => { Values = n.GetObjectValue<global::ApiSdk.Models.Annotation_Values>(global::ApiSdk.Models.Annotation_Values.CreateFromDiscriminatorValue); } },
                { "ViewName", n => { ViewName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AnnotationKey", AnnotationKey);
            writer.WriteEnumValue<global::ApiSdk.Models.Annotation_AnnotationType>("AnnotationType", AnnotationType);
            writer.WriteStringValue("Description", Description);
            writer.WriteStringValue("DocumentationLink", DocumentationLink);
            writer.WriteDateTimeOffsetValue("ExpiresAt", ExpiresAt);
            writer.WriteBoolValue("IsDisabled", IsDisabled);
            writer.WriteCollectionOfPrimitiveValues<string>("Labels", Labels);
            writer.WriteStringValue("Name", Name);
            writer.WriteStringValue("ProjectName", ProjectName);
            writer.WriteStringValue("TimeZone", TimeZone);
            writer.WriteStringValue("Title", Title);
            writer.WriteDateTimeOffsetValue("ValidFrom", ValidFrom);
            writer.WriteObjectValue<global::ApiSdk.Models.Annotation_Values>("Values", Values);
            writer.WriteStringValue("ViewName", ViewName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
