<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>42.Platform.Storyteller.Access.AuthKit.IntegrationTests</AssemblyName>
    <RootNamespace>_42.Platform.Storyteller.Access.AuthKit.IntegrationTests</RootNamespace>

    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Access.AuthKit.csproj" />
  </ItemGroup>

</Project>
