// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Annotation_AnnotationType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Responsibility")]
        #pragma warning disable CS1591
        Responsibility,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unit")]
        #pragma warning disable CS1591
        Unit,
        #pragma warning restore CS1591
        [EnumMember(Value = "Subject")]
        #pragma warning disable CS1591
        Subject,
        #pragma warning restore CS1591
        [EnumMember(Value = "Usage")]
        #pragma warning disable CS1591
        Usage,
        #pragma warning restore CS1591
        [EnumMember(Value = "Context")]
        #pragma warning disable CS1591
        Context,
        #pragma warning restore CS1591
        [EnumMember(Value = "Execution")]
        #pragma warning disable CS1591
        Execution,
        #pragma warning restore CS1591
        [EnumMember(Value = "UnitOfExecution")]
        #pragma warning disable CS1591
        UnitOfExecution,
        #pragma warning restore CS1591
    }
}
