// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MachineAccess : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The AccessKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessKey { get; set; }
#nullable restore
#else
        public string AccessKey { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AnnotationKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnnotationKey { get; set; }
#nullable restore
#else
        public string AnnotationKey { get; set; }
#endif
        /// <summary>The Id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The ObjectId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectId { get; set; }
#nullable restore
#else
        public string ObjectId { get; set; }
#endif
        /// <summary>The Scope property</summary>
        public global::ApiSdk.Models.MachineAccess_Scope? Scope { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.MachineAccess"/> and sets the default values.
        /// </summary>
        public MachineAccess()
        {
            AdditionalData = new Dictionary<string, object>();
            Scope = global::ApiSdk.Models.MachineAccess_Scope.AnnotationRead;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.MachineAccess"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.MachineAccess CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.MachineAccess();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AccessKey", n => { AccessKey = n.GetStringValue(); } },
                { "AnnotationKey", n => { AnnotationKey = n.GetStringValue(); } },
                { "Id", n => { Id = n.GetStringValue(); } },
                { "ObjectId", n => { ObjectId = n.GetStringValue(); } },
                { "Scope", n => { Scope = n.GetEnumValue<global::ApiSdk.Models.MachineAccess_Scope>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AccessKey", AccessKey);
            writer.WriteStringValue("AnnotationKey", AnnotationKey);
            writer.WriteStringValue("Id", Id);
            writer.WriteStringValue("ObjectId", ObjectId);
            writer.WriteEnumValue<global::ApiSdk.Models.MachineAccess_Scope>("Scope", Scope);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
