// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MachineAccess_Scope
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "AnnotationRead")]
        #pragma warning disable CS1591
        AnnotationRead,
        #pragma warning restore CS1591
        [EnumMember(Value = "ConfigurationRead")]
        #pragma warning disable CS1591
        ConfigurationRead,
        #pragma warning restore CS1591
        [EnumMember(Value = "DefaultRead")]
        #pragma warning disable CS1591
        DefaultRead,
        #pragma warning restore CS1591
        [EnumMember(Value = "AnnotationReadWrite")]
        #pragma warning disable CS1591
        AnnotationReadWrite,
        #pragma warning restore CS1591
        [EnumMember(Value = "ConfigurationReadWrite")]
        #pragma warning disable CS1591
        ConfigurationReadWrite,
        #pragma warning restore CS1591
        [EnumMember(Value = "DefaultReadWrite")]
        #pragma warning disable CS1591
        DefaultReadWrite,
        #pragma warning restore CS1591
    }
}
