// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UnitOfExecution : global::ApiSdk.Models.Annotation, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The ContextKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContextKey { get; set; }
#nullable restore
#else
        public string ContextKey { get; set; }
#endif
        /// <summary>The ContextName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContextName { get; set; }
#nullable restore
#else
        public string ContextName { get; set; }
#endif
        /// <summary>The ExecutionKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExecutionKey { get; set; }
#nullable restore
#else
        public string ExecutionKey { get; set; }
#endif
        /// <summary>The ResponsibilityKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResponsibilityKey { get; set; }
#nullable restore
#else
        public string ResponsibilityKey { get; set; }
#endif
        /// <summary>The ResponsibilityName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResponsibilityName { get; set; }
#nullable restore
#else
        public string ResponsibilityName { get; set; }
#endif
        /// <summary>The SubjectKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubjectKey { get; set; }
#nullable restore
#else
        public string SubjectKey { get; set; }
#endif
        /// <summary>The SubjectName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubjectName { get; set; }
#nullable restore
#else
        public string SubjectName { get; set; }
#endif
        /// <summary>The UnitKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnitKey { get; set; }
#nullable restore
#else
        public string UnitKey { get; set; }
#endif
        /// <summary>The UnitName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnitName { get; set; }
#nullable restore
#else
        public string UnitName { get; set; }
#endif
        /// <summary>The UsageKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UsageKey { get; set; }
#nullable restore
#else
        public string UsageKey { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.UnitOfExecution"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::ApiSdk.Models.UnitOfExecution CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.UnitOfExecution();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "ContextKey", n => { ContextKey = n.GetStringValue(); } },
                { "ContextName", n => { ContextName = n.GetStringValue(); } },
                { "ExecutionKey", n => { ExecutionKey = n.GetStringValue(); } },
                { "ResponsibilityKey", n => { ResponsibilityKey = n.GetStringValue(); } },
                { "ResponsibilityName", n => { ResponsibilityName = n.GetStringValue(); } },
                { "SubjectKey", n => { SubjectKey = n.GetStringValue(); } },
                { "SubjectName", n => { SubjectName = n.GetStringValue(); } },
                { "UnitKey", n => { UnitKey = n.GetStringValue(); } },
                { "UnitName", n => { UnitName = n.GetStringValue(); } },
                { "UsageKey", n => { UsageKey = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("ContextKey", ContextKey);
            writer.WriteStringValue("ContextName", ContextName);
            writer.WriteStringValue("ExecutionKey", ExecutionKey);
            writer.WriteStringValue("ResponsibilityKey", ResponsibilityKey);
            writer.WriteStringValue("ResponsibilityName", ResponsibilityName);
            writer.WriteStringValue("SubjectKey", SubjectKey);
            writer.WriteStringValue("SubjectName", SubjectName);
            writer.WriteStringValue("UnitKey", UnitKey);
            writer.WriteStringValue("UnitName", UnitName);
            writer.WriteStringValue("UsageKey", UsageKey);
        }
    }
}
#pragma warning restore CS0618
