// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiSdk.V1.Item.Item.Item.Executions
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\{organization}\{project}\{view}\executions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExecutionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Item.Item.Item.Executions.ExecutionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExecutionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/{organization}/{project}/{view}/executions{?contextNameQuery*,continuationToken*,responsibilityNameQuery*,subjectNameQuery*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Item.Item.Item.Executions.ExecutionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExecutionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/{organization}/{project}/{view}/executions{?contextNameQuery*,continuationToken*,responsibilityNameQuery*,subjectNameQuery*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::ApiSdk.Models.AnnotationsResponse_Execution"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiSdk.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::ApiSdk.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ApiSdk.Models.AnnotationsResponse_Execution?> GetAsync(Action<RequestConfiguration<global::ApiSdk.V1.Item.Item.Item.Executions.ExecutionsRequestBuilder.ExecutionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ApiSdk.Models.AnnotationsResponse_Execution> GetAsync(Action<RequestConfiguration<global::ApiSdk.V1.Item.Item.Item.Executions.ExecutionsRequestBuilder.ExecutionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ApiSdk.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::ApiSdk.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ApiSdk.Models.AnnotationsResponse_Execution>(requestInfo, global::ApiSdk.Models.AnnotationsResponse_Execution.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.V1.Item.Item.Item.Executions.ExecutionsRequestBuilder.ExecutionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.V1.Item.Item.Item.Executions.ExecutionsRequestBuilder.ExecutionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.V1.Item.Item.Item.Executions.ExecutionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ApiSdk.V1.Item.Item.Item.Executions.ExecutionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ApiSdk.V1.Item.Item.Item.Executions.ExecutionsRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class ExecutionsRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            /// <summary>The name query to filter the executions by context.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("contextNameQuery")]
            public string? ContextNameQuery { get; set; }
#nullable restore
#else
            [QueryParameter("contextNameQuery")]
            public string ContextNameQuery { get; set; }
#endif
            /// <summary>The continuation token for multi-page queries.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("continuationToken")]
            public string? ContinuationToken { get; set; }
#nullable restore
#else
            [QueryParameter("continuationToken")]
            public string ContinuationToken { get; set; }
#endif
            /// <summary>The name query to filter the executions by responsibility.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("responsibilityNameQuery")]
            public string? ResponsibilityNameQuery { get; set; }
#nullable restore
#else
            [QueryParameter("responsibilityNameQuery")]
            public string ResponsibilityNameQuery { get; set; }
#endif
            /// <summary>The name query to filter the executions by subject.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("subjectNameQuery")]
            public string? SubjectNameQuery { get; set; }
#nullable restore
#else
            [QueryParameter("subjectNameQuery")]
            public string SubjectNameQuery { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExecutionsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ApiSdk.V1.Item.Item.Item.Executions.ExecutionsRequestBuilder.ExecutionsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
